apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: angular-ui
  labels:
    app: angular-ui
spec:
  serviceName: angular-ui-service 
  replicas: 1
  selector:
    matchLabels:
      app: angular-ui
  template:
    metadata:
      labels:
        app: angular-ui
    spec:
      containers:
      - name: angular-ui
        image: demo-angular:v0303.05
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-ui-service
spec:
  type: NodePort
  selector:
    app: angular-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31121
