apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: angular-ui
  labels:
    app: angular-ui
spec:
  serviceName: angular-ui-service 
  replicas: 1
  selector:
    matchLabels:
      app: angular-ui
  template:
    metadata:
      labels:
        app: angular-ui
    spec:
      nodeSelector:
        kubernetes.io/hostname: bseitrspoc2.bseindia.com
      containers:
      - name: angular-ui
        image: app-angular:v153.01
        imagePullPolicy: Never
        ports:
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: angular-ui-service
spec:
  type: NodePort
  selector:
    app: angular-ui
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 31121
