apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: middleware
  labels:
    app: middleware
spec:
  serviceName: middleware-service 
  replicas: 1
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      nodeSelector:
        kubernetes.io/hostname: bseitrspoc2.bseindia.com
      containers:
      - name: middleware
        image: app-middleware:v173.01
        env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
        imagePullPolicy: Never
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: middleware-service
spec:
  type: NodePort
  selector:
    app: middleware
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
    nodePort: 31127
