apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mock-sender
  labels:
    app: mock-sender
spec:
  serviceName: mock-sender-service 
  replicas: 0
  selector:
    matchLabels:
      app: mock-sender
  template:
    metadata:
      labels:
        app: mock-sender
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: mock-sender
      containers:
      - name: mock-sender
        image: app-sender:v173.02
        env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mock-sender-service
spec:
  selector:
    app: mock-sender
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
