apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processor
  template:
    metadata:
      labels:
        app: data-processor
    spec:
      containers:
      - name: data-processor
        image: data-processor:v16
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: redis-config
        ports:
        - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: data-processor-service
spec:
  selector:
    app: data-processor
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001