apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  master-redis: "3.87.124.164"
  secondary-redis-template: "secondary-redis-service-{pod-index}:6379"
  aws-eti-server: "3.89.228.214"